name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version: ['1.19','1.20','1.21.x']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: |
          go get .
          go get example.com/octo-examplemodule
          go get example.com/octo-examplemodule@v1.3.4

